### ISSUE TITLE
IMMEDIATE TODO

### ISSUE THREAD

**Issue by ks0m1c** [paperlands/dojo#2]
- [x]  1D Elementary cellular automaton @KosmonautX 
  - [x]  Ruleset for the 8 possible 3 cell (1 center- 2 neighbour) states (alive/dead representation) @KosmonautX
  - [x] visualisation of ruleset (graphic) or like that wikipedia
  - [x] Next Generation state animation @KosmonautX 
  - [x]  Tree like multiple generations in one frame @KosmonautX 

- [ ]  Sensei Liveview
  - [x]  Pubsub machinery to class:book1 topic from sensei liveview
  - [x] handle infos on Book1 liveview for
    - [x] teacher box focus on other students orange box to discuss further
  - [ ] teacher view of students on error states (proper errorhandling so teacher liveview is robust doesn't crash)

- [ ]  Curriculum 
  - [ ] **Convolution** addenum image white box with student led kernels as orange boxes
  - [ ] universal computation using glider guns thru gates
  - [ ]  https://cba.mit.edu/events/03.11.ASE/docs/VonNeumann.pdf

![](https://upload.wikimedia.org/wikipedia/commons/e/e2/One-d-cellular-automate-rule-30.gif)

- [ ] Support of rulesets in 2D conway for (whitebox)
- [ ] Proper Errorhandling for unexpected states on 2D @KosmonautX 
- [x]  get it out of localhost
  - [x] deploy with livebooks ecto_ipv6

- [ ] Whitebox
  - [ ] Teacher(White)Box Focus so teacher can take over
    - [ ] teacher triggered event to reveal student whiteboxes(free play) and to freeze them
  - [ ] teacher view to see all whiteboxes that can be frozen or revealed

low prio...
- [ ] abstracting and cleaning up cells, kernels, game primitives 

- [ ] to give student control
  - [ ] name field on student book (back it up into localstorage)
  - [ ] teacher list of which student is live and trigger event to give control to
  - [ ] student god view ability of focusing on their classmates orange boxes like a teacher or take over of teacher(white) box functions

**Comment by PrincetonPoh** [comment]
User story script:
1 student works on livebook and input their own init state
2 student publish to liveview
3 --everyone looks at liveview on projector--
4 teacher introduce kernel rule 1
4a everyone copies kernel code to their own livebook
4b students publishes their livebook kernel
4c --activity: everyone find their own fav rule--
4e student likes rule 2
5 student input their kernel rule 2 into livebook
6 student publish kernel rule 2 to liveview
7 --everyone looks at liveview on the projector--
8 teacher introduces space time diagram (triangle)
9 ~end of 1D~
